name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  firebase_database: ^10.4.4
  firebase_storage: ^11.5.5
  cloud_firestore: ^4.15.4
  flutter_local_notifications: ^17.1.2
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  lottie: ^2.7.0
  fl_chart: ^0.63.0
  intl: ^0.18.1   # ✅ Pour le formatage des dates

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/pill_box_logo.jpeg
    - lib/assets/animations/icon.json
    - lib/assets/animations/loading.json
    - lib/assets/animations/medication.json
    - lib/assets/animations/waiting.json
    - lib/assets/images/google_icon.png
