// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwLxmwJ4LCO3fwDLAlvHHAkHYjP1UxAH0',
    appId: '1:439870589264:android:de4bc54bac04b482e10455',
    messagingSenderId: '439870589264',
    projectId: 'iot-projet-32bdb',
    databaseURL: 'https://iot-projet-32bdb-default-rtdb.firebaseio.com',
    storageBucket: 'iot-projet-32bdb.appspot.com', // ✅ correction ici
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RqVtvZ0GyHZY1q9ybP83QBMXP98PBaQ',
    appId: '1:439870589264:ios:7fac40429024f46fe10455',
    messagingSenderId: '439870589264',
    projectId: 'iot-projet-32bdb',
    databaseURL: 'https://iot-projet-32bdb-default-rtdb.firebaseio.com',
    storageBucket: 'iot-projet-32bdb.appspot.com', // ✅ correction ici
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCADn7CAYZMeYpcNLFjqQlC70rbwVTPDVo',
    authDomain: 'iot-projet-32bdb.firebaseapp.com',
    databaseURL: 'https://iot-projet-32bdb-default-rtdb.firebaseio.com/',
    projectId: 'iot-projet-32bdb',
    storageBucket: 'iot-projet-32bdb.appspot.com', // ✅ correction ici
    messagingSenderId: '439870589264',
    appId: '1:439870589264:web:38187494d4c04d85e10455',
    measurementId: 'G-HEB1HFEHDZ',
  );
}
